--- 9.  If each $1 spent equates to 10 points and sushi 
--- has a 2x points multiplier - how many points would each customer have?
-- 10. In the first week after a customer joins the program 
---- (including their join date) they earn 2x points on all items, not just sushi - how many points do customer A and B have at the end of January?
